<script lang="ts">
	export const prerender = true;
    import Icon from '@iconify/svelte';
</script>

<svelte:head>
	<title>Info</title>
	<meta name="Prezenti - Info" content="About Prezenti" />
</svelte:head>

<section>
<div class="corner">
    <a class="corner-a" aria-label="Link to go back" sveltekit:prefetch href="/links">
        <Icon icon="mdi:arrow-left" />
    </a>
</div>


<div class="history-typewriter">
    
    <div class="container">
        <div  class="content">
            <h1>GRANTS</h1>
        </div>
    </div>

        <div class="container-typewriter ">
            <div  class="content-typewriter">

                <h2>2heavens</h2>

                <p>They were born during the DeFi for The People hackathon.</p>
                <p>They transform people's relationship with their wealth and inheritance through clarity of information about their crypto assets.</p>
                <p>A wallet that will help educate people in the crypto world, and also keep the assets visible to the heirs. The grant will be used for this and to implement the features below:</p>
                <ul>
                    <li>TTOD (Token Transfer on death)</li>
                    <li>Joint wallet with children to educate them on investments</li>
                    <li>Crypto Risk Prediction- Asset Evolution Dashboard</li>
                </ul>
                <br/>
                <li><a href="https://dapplooker.com/">Website</a></li>
                <li><a href="https://twitter.com/dapplooker">Twitter</a></li>

                <hr/>

                <h2>Alcancia</h2>

                <p>Alcancia is a native mobile application. A wallet that lets users bridge their fiat Mexican and Dominican pesos into stablecoins (USDC and cUSD).</p>
                <li><a href="https://mirror.xyz/0x86792D8d875a06ccC787096304647aA98C5FB9Bb">Mirror</a></li>
                <li><a href="https://landing.alcancia.io/">Website</a></li>
                <li><a href="https://twitter.com/Alcancia_io">Twitter</a></li>

                <hr/>

                <h2>Arttribute</h2>

                <p>Arttribute aims to address the growing prevalence of AI-generated art by empowering artists and offering transparent and ethical usage of artwork in generative AI models. The goal is to provide tools that cater to the needs of artists, AI enthusiasts, and practitioners, providing them with a seamless and ethical way to collaborate and promote fair and transparent usage of artwork.</p>

                <hr/>

                <h2>Community Health Project (TogetherCrew)</h2>

                <p>This project contributes to Celo’s mission of building an open financial system that creates the conditions of prosperity for all by developing tools to measure and analyze community health and governance participation within Celo’s ecosystem. By defining a framework for evaluating community health, collecting data on community engagement, and analyzing it to identify patterns and trends, the project aims to provide insights that can be used to improve community engagement and participation, and ultimately help to create the conditions of prosperity for all. The involvement of research partners from MIT and UC Berkeley also demonstrate the commitment to applying scientific rigor in this process.</p>
                <li><a href="https://discord.com/invite/Pk4GasVFr5">Discord</a></li>
                <li><a href="https://twitter.com/RnDAO__">Twitter</a></li>

                <hr/>

                <h2>BitGifty</h2>

                <p>Bitgifty is an innovative crypto gift card platform that enables users to send and receive crypto as gift cards via email. Users can easily create and redeem crypto gift cards in just a few clicks, sending cUSD, Celo, Bitcoin, Ethereum, USDT, and other coins as gift cards.
                    With BitGifty, users can receive crypto directly in their email without worrying about wallet addresses. Not only can users receive crypto gifts seamlessly, but they can also either convert the gifts to Naira directly to their bank account or spend the gift right on the platform.
                    BitGifty provides its users with the option to pay for their daily utilities using their crypto gifts, such as data, airtime, cable TV, and electricity bills.</p>
                <li><a href="https://bitgifty.com/">Website</a></li>
                <li><a href="https://twitter.com/BitGifty">Twitter</a></li>

                <hr/>

                <h2>Cred Protocol</h2>

                <p>Cred Protocol helps previously unbanked people establish creditworthiness by analysing on-chain activity generated by interactions with UBI protocols like Impact Market and Good Dollar and MSME projects like Jia. Efficiently quantifying credit risk is crucial for enabling access to loans and other financial products for individuals and businesses. Building a credit bureau on decentralized blockchain infrastructure enables creditworthiness to be evaluated using open, fair and transparent data and ultimately offers the opportunity for credit models themselves to be open and transparent. This is the foundation for a global credit risk infrastructure that promotes financial inclusion and enables people in emerging markets to access capital from around the world distributed through Celo and other blockchains.</p>
                <p>This project aims to enable UBI recipients in emerging economies to establish creditworthiness.  By measuring, monitoring and reporting on-chain activity, individuals and businesses can demonstrate creditworthy behaviour that may enable access to microloans from projects such as Jia.</p>
                <li><a href="https://app.credprotocol.com/">Website</a></li>
                <li><a href="https://twitter.com/cred_protocol?lang=en">Twitter</a></li>

                <hr/>

                <h2>DappLooker</h2>

                <p>This project is to work closely with the Celo Dapps, integrate their contracts/subgraphs on our platform, and launch their analytics solutions. Dapps data and dashboards will be available for community analytics.</p>
                <p>They are aiming to onboard 15 current and future Celo Dapps and five network tokens.</p>
                <p>Most of these dapps need premium features such as export to CSV, embedding on their website, API with higher rate limits, user retention dashboards, and more.</p>
                <li><a href="https://dapplooker.com/">Website</a></li>
                <li><a href="https://twitter.com/dapplooker">Twitter</a></li>

                <hr/>

                <h2>Ethics for a Humanized Technological Development</h2>

                <p>Ethics for a Humanized Technological Development is planning a 6 month project, where they will educate high school and college students on the foundations of blockchain technology and ethics of token engineering. Their main focus will be public schools in Salvador, Brazil, and the course will help onboard students to Celo and its Dapps, with a focus on how blockchain can improve the lives of different communities.</p>
                <li><a href="https://www.notion.so/Blockchain-na-Escola-DAO-8cacb7e784694c3695b7b13abd882bda">Notion</a></li>
                <li><a href="https://blockchainnaescola.tech/en">Website</a></li>
                <li><a href="https://twitter.com/BlckNaEscola">Twitter</a></li>

                <hr/>

                <h2>Giveth</h2>

                <p>The Giveth community intention is to support and reward the funding of public goods by creating open, transparent and free access to the revolutionary funding opportunities available within the Ethereum ecosystem. With funding from Prezenti they plan to add the ‘Donation Application’ to the Celo chain so that every project on Giveth can raise funds with Celo. On their DApp, 100% of donations go directly to the project and Donors to verified projects are rewarded with GIVbacks. </p>
                <li><a href="https://giveth.io/">Website</a></li>
                <li><a href="https://twitter.com/Givethio">Twitter</a></li>

                <hr/>

                <h2>Green Digital Guardians</h2>

                <p>GDG purpose is to create the Largest Community on Planet Earth «Digital Guardians of The GreenArks» through new NFT technologies. Using Prezenti funding they aim to really kick things off the ground, including: design and trademark registration, building mark reputation and social media channels, create the non-profit organization, and design first NFT Collection.</p>
                <li><a href="https://dgguardians.com">Website</a></li>
                <li><a href="https://twitter.com/dg_guardians">Twitter</a></li>

                <hr/>

                <h2>Gigawatt</h2>

                <p>Gigawatt is an asset backed debt-financing protocol for the renewable energy sector that will supercharge the green-energy transition by originating investment-grade renewable energy sources as RWAs on the Celo blockchain.</p>
                <li><a href="https://gigawa.tt/">Website</a></li>
                <li><a href="https://twitter.com/0xGigawatt">Twitter</a></li>

                <hr/>

                <h2>Hack Culture: The Black History Month Edition</h2>

                <p>#HackCulture is a hackathon series for devs building DeFi for the real world. Prezenti funding will pay for a case study after their next big event in February 2023 , New York, USA. The event will market Celo to a more diverse developer and user base that Celo isn’t currently reaching. They’ll use videos, audio, articles, newsletters, and social media accounts across YouTube, Twitter, TikTok, Linkedin, Instagram, and Clubhouse to maximize reach</p>
                <li><a href="https://www.audacity.fund/">Website</a></li>
                <li><a href="https://twitter.com/audacity_fund">Twitter</a></li>

                <hr/>

                <h2>Hurupay</h2>

                <p>Hurupay is a self custodial wallet that allows users to buy and hold cryptocurrencies such as stablecoins, while giving them ability to pay, remit and transact crypto securely. It is built on the Celo blockchain and allows unbanked to be banked through cUSD.</p>
                <li><a href="https://www.hurupay.com/">Website</a></li>
                <li><a href="https://twitter.com/HurupayApp">Twitter</a></li>

                <hr/>

                <h2>ImpactMarket</h2>

                <p>Impact Market is an open protocol that unlocks access to finance and unconditional basic income to almost 50K beneficiaries from ~30 developing countries living in 220+ very vulnerable communities.</p>
                <p>The objective of this funding is to develop a combination of mechanisms to drive inflow of funds without the need for "traditional" donations, increasing the economic impact multiplier while enabling UBI to scale sustainability as a way to drive significant adoption and retention.</p>
                <li><a href="https://www.impactmarket.com/">Website</a></li>
                <li><a href="https://twitter.com/impactMarket_">Twitter</a></li>

                <hr/>

                <h2>Inclusive blockchain for Africa (ib4a)</h2>

                <p>Inclusive Blockchain for Africa (IB4A) is a project under Decentralized Future in Motion Lab Limited to educate technical and non-technical individuals on the possibilities of blockchain technology. They expose non-technical people to blockchain fundamentals and train technical individuals on how to build decentralized applications on the Celo blockchain. So far they have trained over thirty developers on building DApps on the Celo blockchain using solidity.</p>
                <p>Their goal with Prezenti support is to train one thousand developers on building DApps on the Celo blockchain using available tools from Celo.</p>
                <li><a href="https://learn.dfmlab.com/">Website</a></li>
                <li><a href="https://twitter.com/dfmlabltd">Twitter</a></li>

                <hr/>

                <h2>Into the Verse</h2>

                <p>IntotheVerse is developing an on-chain mobile game on Celo Blockchain where players can engage in building their own world, manage and nurture it, meet with other players and perform activities that we perform in the real world (farming, fishing, banking, recreation, conservation) from within the game, in a social and educational gameplay focused on onboarding people to web3 and simplifying web3 UX through gamification.</p>
                <li><a href="https://intotheverse.xyz/">Website</a></li>
                <li><a href="https://twitter.com/IntoTheVerse_">Twitter</a></li>

                <hr/>

                <h2>Inspira Valley</h2>

                <p>InspiraValley plans to develop a special edition dedicated to product management in Celo Blockchain, demonstrating the ReFi Product Model Canvas framework with use cases, innovative Brazilian projects in Celo, podcast with Brazilian entrepreneurs on Celo, videos on blockchain product management and presenting global solutions developed in Celo Blockchain.</p>
                <li><a href="https://www.inspiravalley.com/">Website</a></li>
                <li><a href="https://twitter.com/inspiravalley">Twitter</a></li>

                <hr/>

                <h2>Love Crypto</h2>

                <p>Love Crypto is a Proof of Concept for interoperability on the Brazilian Real Digital Ledger into a full-fledged product to allow users to purchase Real World Assets registered in the Real Brazilian Digital Ledger.</p>
                <li><a href="http://liftlabs.lovecrypto.com.br:3000/">Proof of Concept</a></li>
                <li><a href="https://www.lovecrypto.net/#/">Website</a></li>
                <li><a href="https://twitter.com/Lovecryptobr">Twitter</a></li>

                <hr/>

                <h2>Nerve Network</h2>

                <p>NerveNetwork is an asset relay network connecting multiple blockchains, a 0 gas blockchain.
                    NerveNetwork aims to connect all isolated blockchains and establish a cross-chain asset exchange network, providing all necessary underlying support for DeFi ecosystem.Let every digital asset holder experiences a truly secure, free and transparent DeFi application service.
                    Nerve Network is doing an integration to support cross chain liquidity between Celo and Nerve. This will allow Nerve Network to support Celo assets and all the Celo blockchain based assets cross chain to the other 26+ supported blockchains on NerveBridge.</p>
                <li><a href="https://nerve.network/">Website</a></li>
                <li><a href="https://twitter.com/nerve_network">Twitter</a></li>

                <hr/>

                <h2>Onboard</h2>

                <p>Onboard is a community of builders who are gathered to create educational content to support ecosystems. By funding Onboard, they will aim to engage these builders to educate the world on building on Celo through product development and content creation.</p>
                <li><a href="https://onboard.super.site/">Website</a></li>
                <li><a href="https://twitter.com/jackietanyen">Twitter</a></li>

                <hr/>

                <h2>Onset Carbon</h2>

                <p>The Onset Carbon project aims to make offsetting carbon emissions easy and accessible for
                    companies through the development of a blockchain-based API. The API will utilize carbon credits from the Verra registry, which will be bridged to the Celo blockchain via the Toucan protocol. This will provide a secure and robust platform for fast and low-cost transactions, while also allowing for enhanced verification and auditability of carbon credits. They also have a storefront which allows anyone to quickly and easily offset their emissions with a credit card using blockchain-based credits, which they built as a proof of concept.</p>
                <li><a href="https://www.onsetcarbon.com/">Website</a></li>

                <hr/>

                <h2>Ostrom</h2>

                <p>Ostrom is a protocol for community-based development and environmental regeneration. Communities and individuals can deposit their land or purchase Ostrom independently to be invested in a land asset. Ostrom enables a network of Community Land Trust’s to be formed and dynamic management of land.</p>
                <li><a href="https://www.de-plan.xyz/">Website</a></li>
                <li><a href="https://twitter.com/de_planDAO">Twitter</a></li>

                <hr/>

                <h2>Procision</h2>

                <p>Procision aims to solve the problem of the increasing number of payment options available to consumers, including multiple currencies, loyalty points, and digital tokens. Their solution provides retailers with a single platform to manage pricing and transactions for all types of payments and redemptions, reducing the need to navigate multiple silos to set prices across the board.
                    In addition, they help address climate remediation by enabling consumers to retire carbon pollution through everyday retail purchases or loyalty redemptions. Their platform also provides an auditable way for retail businesses to contribute to climate remediation efforts.
                    They plan to integrate Celo tokens into our product to enable customers to pay for products with Celo or a white-labeled Celo coin. Customers will also receive Celo coins as rewards for their purchases, thereby promoting the use of Celo beyond its climate benefits.</p>
                <li><a href="https://procision.co/">Website</a></li>
                <li><a href="https://twitter.com/procision_co">Twitter</a></li>

                <hr/>

                <h2>Rebiocca</h2>

                <p>Rebioca aims to design the products of the future by recycling organic wastes with low carbon emissions, water use, and energy use. Rebioca is helping our planet with the organic waste process as we have been working with “nature’s gift” black soldier flies. We process organic waste in a much green way and produce protein-rich end products such as fertilizer, BSF oil, and many more while reducing x0.4 carbon emissions per tonne compared to traditional methodologies.</p>
                <li><a href="https://www.rebioca.com/">Website</a></li>
                <li><a href="https://twitter.com/rebioca">Twitter</a></li>

                <hr/>

                <h2>ReFi Hub</h2>

                <p>In line with Celo’s mission, they aim to create a more open, equitable system of global finance, which creates prosperity for all, including people and the planet. ReeFi Hub will connect real world economies with the world of DeFi. This decentralized model will allow every day people to provide liquidity to a typically inaccessible and inequitable market. In doing so, users will be able to create stable and consistent returns on their investments, regardless of where they are in the world, or how much money they have to invest. ReeFi Hub also tackles one of the most pressing issues of our time; climate change. By giving financial power and a community platform to every day people around the world, ReeFi Hub will ensure that people do not need to make the choice of whether to prioritize their personal financial success or contributing to climate solutions.</p>
                <li><a href="https://www.coraltribe.io/">Website</a></li>
                <li><a href="https://twitter.com/CoralTribeNFT">Twitter</a></li>

                <hr/>

                <h2>ReFi Medellín</h2>

                <p>They are a movement dedicated to creating a more sustainable and equitable future in Medellín.
                   Their goal is to foster community discussions around regenerative-oriented-innovations (ROIs) enabled by Web3 and empower the city's youth to address some of its most pressing challenges through hackathons, incubation, and investment. These challenges include poverty, inequality, youth unemployment, and the lack of access to basic resources such as energy, water, sanitation, housing, and education.</p>
                <li><a href="https://linktr.ee/refimedellin">Website</a></li>
                <li><a href="https://twitter.com/ReFiMedellin">Twitter</a></li>

                <hr/>

                <h2>ReFi Paramaribo</h2>

                <p>They are seeking this grant to fund the launch of ReFi Paramaribo, a regenerative finance community that aims to increase financial literacy and access to funding for underrepresented groups and individuals in Paramaribo, Suriname. The proposal for this project includes establishing an online presence, hosting educational and networking events, and launching seed funding and mentorship programs.</p>
                <li><a href="https://www.innovatorsbuzz.org/">Website</a></li>
                <li><a href="https://www.twitter.com/ReFiParamaribo">Twitter</a></li>

                <hr/>

                <h2>Sargo</h2>

                <p>Sargo is a decentralized protocol for swapping between stablecoins and local currencies from your phone. Over time they aim to integrate Sargo into a range of 3rd-party wallets, dapps and interfaces. Making it cheaper and easier to enter and exit the web-3 economy without the need for a token bridge, order book, fiat integration, or pooling mechanism</p>
                <li><a href="https://twitter.com/sargo_io">Twitter</a></li>

                <hr/>


                <h2>Tali AI</h2>

                <p>Tali is an intelligent, AI-driven Discord bot designed to enhance developer relations, support, and community management. Tali instantly answers developer questions by analyzing developer docs, technical documentation, and other data sources for seamless knowledge integration for technical support.</p>
                <li><a href="https://www.trytali.com/">Website</a></li>
                <li><a href="https://twitter.com/trytaliAI">Twitter</a></li>

                <hr/>

                <h2>Teleport DAO Bridge</h2>

                <p>Teleport Bridge is a light client bridge between Celo and Ethereum, It is a part of Teleportdao which is a trustless interoperability protocol. So far, they have built a bridge between Bitcoin and EVM chains, they are now live on Polygon. They will soon launch their light client  bridge between Bitcoin and Ethereum. As a team, they have built applications on top of their live bridge:</p>
                    <li><a href="https://teleswap.xyz/">Teleswap</a>: which is a Dex for Bitcoin and tokens on polygon</li>
                    <li><a href="https://teleordinal.xyz">TeleOrdinal</a>: which is a decentralized marketplace for Ordinals</li>
                    <p>Other links</p>
                    <li><a href="https://www.teleportdao.xyz/">Website</a></li>
                    <li><a href="https://twitter.com/Teleport_DAO">Twitter</a></li>

                <hr/>

                <h2>TokPay</h2>

                <p>Tokpay is an African Focused web 3 Neobank for high-yield USD savings and Fixed Deposit Accounts.</p>
                <li><a href="http://tokpayapp.com/">Website</a></li>
                <li><a href="https://twitter.com/tokpayapp">Twitter</a></li>

                <hr/>

                <h2>Wasset</h2>

                <p>Wasset's mission of creating a waste-powered circular economy that ensures sustainable collection, recovery, and recycling of waste aligns with Celos mission of creating a financial system that creates prosperity for all while contributing positively to the well-being of our planet. Prezenti is supporting a pilot program, which is focused on encouraging sorting, collection, and recycling of waste, to test the community response to the ImpactUs and UBHI programs.</p>
                <li><a href="https://wasset.io/">Website</a></li>
                <li><a href="https://twitter.com/wassetltd">Twitter</a></li>

                <hr/>

                <h2>Quidli</h2>

                <p>Quidli is a token rewards tool for crypto organisations to keep their communities engaged natively in Slack and Discord. Their app enables you to recognise your active community members for their contributions, such as social media participation. They are currently used by community teams in ConsenSys, NEAR, iExec, Flare Network, Concordium, CUDOS and MAP Protocol. WIth funding from Prezenti they will be adding cUSD, cEUR and cREAL as an option to share rewards in the Celo discord. That’s right, you will then be able to tip or support fellow community members in Celo stables!</p>
                <li><a href="https://twitter.com/quidliprotocol">Twitter</a></li>
                <li><a href="https://quid.li/">Website</a></li>
                <hr/>



        </div>

                
                
        </div>

        </div>

</section>


<style>
    hr {
        margin-top: 50px;
        margin-bottom: 50px;
    }
    section {
        margin-bottom: 40px;
    }

	.history-animation {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		height:100vh;
        margin-top: -10%;
	}

    .history-typewriter {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
        margin-top: -10%;
        padding-bottom: 5%;
	}

    .container {
        flex-wrap: wrap;
        min-height: 15vh;
        width:20%;
        display: flex;
        justify-content: center;
        align-items: center;
        color: var(--mdc-theme-on-secondary, #fff);
    }

    .container-typewriter {
        flex-wrap: wrap;
        padding-top: 5%;
        min-height: 15vh;
        width:80%;
        margin:auto;
        display: flex;
        justify-content: center;
        align-items: center;
        color: var(--mdc-theme-on-secondary, #fff);
    }

    .content-typewriter {
        justify-content: center;
        align-items: center;
        margin: auto;
        font-size: 1rem;
        color: var(--text-color);
    }

    .content-typewriter p {
        color: var(--text-color);
    }

    h1 {
        margin-top:7%;
        margin-bottom: 2%;
        font-family: 'VECTRO-bold';
        font-size: 3rem;
        line-height: 100%;
    }

 

    .focus-area-image {
        height: 100px;
    }

    h2 {
        font-weight: bold;
        font-size: 1.5rem;
        margin-bottom:2%;
        font-family: 'VECTRO-bold';
        line-height: 100%;
        
    }

    p {
        font-family: 'Roboto', sans-serif;

        margin-top:3px;
    }

    accordian {
        font-family: 'Roboto', sans-serif;
        text-align: center;
        align-items: center;
        margin-top:3px;
    }



    .apply-text {
        font-family: 'Roboto', sans-serif;
        text-align: left;
        align-items: left;
        margin-top:3px;
    }

    .content {
        justify-content: center;
        align-items: center;
        margin: auto;
        font-size: 3rem;
    }

    img {
        object-fit:fill;
        width:100%;
    }

    .corner a {
            font-size: 5rem;
            color:var(--text-color);
         }

    .corner-a:hover {
        color:var(--text-color);
        opacity: 0.5;

    } 

    a {
        text-decoration: none;
        color: var(--secondary-color)
    }

    p a:hover {
        color:black;
        background-color:#44d8f2 ;
        opacity: 0.5;
    }

    .corner {
        padding:5%;
		width: 1rem;
		height: 1rem;
	}

    .corner img {
        width: 3rem;
        height: 3rem;
    }


    @media (max-width: 600px) {
        a {
            font-size: 4rem;
        }

    }

    @media (max-width: 400px) {


        
        a {
            font-size: 0.7rem;
        }

        .content-typewriter {
            font-size: 0.7rem;
        }

        .history-typewriter {
            margin-top: -20%;
        }

        .container {
            margin-top:10%
         }

         .corner a {
            font-size: 2.4rem;
         }
    }

    

	
</style>